# finds - Copyright (c) 2026 Kirizaki

[pytest]
pythonpath = .
# 30 minutes default timeout
timeout = 1800
markers = 
    # faults classes
    contentions: all contentions tests
    thread_contentions: thread contentions tests
    io_contentions: i/o contentions tests
    cpu_contentions: cpu contentions tests
    deadlocks: circular-wait deadlocks tests
    hazards: hazards / race condition (ie. TOCTOU) tests

    negative: fault injection tests
    long: long-running tests
    stress: long-running stress test
