# finds - Copyright (c) 2026 Kirizaki
name: Weekend stress tests

on:
  schedule: 
    - cron: "00 22 * * 5"  # every Friday 22:00

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name : Setup uv
      uses: astral-sh/setup-uv@v6

    - name: Setup dependencies
      run: uv sync

    - name: Run tests
      run: |
        uv run pytest -s -v -m "stress" --junitxml=results/junit.xml --html=results/report.html --self-contained-html

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: stress-test-results
        path: |
          results/junit.xml
          results/report.html
